//
// Created by farshid on 6/21/21.
//

#ifndef SIMPLE_INTENT_DETECTION_RULESMANAGER_H
#define SIMPLE_INTENT_DETECTION_RULESMANAGER_H


class RulesManager {

};


#endif //SIMPLE_INTENT_DETECTION_RULESMANAGER_H
