# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: "ubuntu:bionic"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install PTHREAD
          command: 'apt-get update && sudo apt-get install -y libpthread-stubs0-dev'
      - run:
          name: Install GTEST
          command: 'apt-get update && sudo apt-get install -y libgtest-dev'
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir build
            cd build
            cmake ..
            make
      - run:
          name: Execute Tests
          command: |
            cd assessment-tests
            mkdir build
            cd build
            cmake ..
            make
            ./assessment-tests --gtest_output=XML
      - store_test_results:
          path: build
